# Generated by Django 5.2.1 on 2025-06-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=15)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('entry_year', models.PositiveIntegerField(blank=True, null=True)),
                ('education_cycle', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], max_length=10)),
                ('reason', models.CharField(blank=True, help_text='Required for Clock Out: e.g., Health, Fees, Holiday, Discipline', max_length=255, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
