# Generated by Django 5.2.1 on 2025-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='reason',
            field=models.CharField(blank=True, choices=[('fees', 'School Fees'), ('holiday', 'Holiday'), ('sick', 'Sick Leave'), ('midterm', 'Mid-Term'), ('discipline', 'Discipline'), ('health', 'Health Checkup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], max_length=10),
        ),
    ]
