# Generated by Django 5.2.1 on 2025-06-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancelog_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultClockOutReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(choices=[('fees', 'School Fees'), ('holiday', 'Holiday'), ('sick', 'Sick Leave'), ('midterm', 'Mid-Term'), ('discipline', 'Discipline'), ('health', 'Health Checkup')], max_length=20)),
            ],
        ),
    ]
