# Generated by Django 5.2.1 on 2025-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_defaultclockoutreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
