# Generated by Django 5.2.1 on 2025-07-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancelog_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='unique_id',
            field=models.CharField(blank=True, default='import uuid; uuid.uuid4().hex', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
