# Generated by Django 5.2.1 on 2025-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='log_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
